### ISSUE TITLE
iOS: export file location moved 

### ISSUE THREAD

**Issue by devohp** [felixlen/ena_log#3]
Hi, 
the iOS export file location moved in iOS14 (i assume) to:
Einstellungen / Begegnungsmitteilungen / Status von Begegnungsaufzeichnungen / Begegnungsüberprüfungen / [FaceID] / Überprüfungen exportieren
No big deal...

**Comment by felixlen** [comment]
Hi,

thanks a lot for the updated description, I have adapted the information.
