### ISSUE TITLE
iOS: not working

### ISSUE THREAD

**Issue by devohp** [felixlen/ena_log#4]
Hi,
if I'm using the iOS export, the parsing takes 1 second and reports: "Bei Begegnungsüberprüfungen wurden keine Treffer mit positiv getester Person gefunden." (the CWA reports 1 encounter). If I'm reformatting the file manually (deleting everything before "[{"Timestamp"" and after ""}]") the processing takes for a long time without any result). Am I missing a step?
TIA

**Comment by felixlen** [comment]
Hi,
are you running the latest iOS version (update from this week)? This sounds like an iOS Bug that has been fixed in the latest version, see https://github.com/corona-warn-app/cwa-app-ios/issues/1106.

**Comment by devohp** [comment]
iOS 14.0.1, will update to 14.1

**Comment by devohp** [comment]
Unfortunately no difference after updating to iOS 14.1, CWA 1.5.1(1)

**Comment by felixlen** [comment]
I think the update only takes effect after the next check of CWA, so you need to wait for eventually another 24 hours. Please note that there is another bug in parsing the log file of iOS 14.1 since apple changed the way file hashes are calculated. I intend to fix it today/tomrrow, see also #5.

**Comment by felixlen** [comment]
A workaround for #5 is implemented and everything should work as supposed to work.

**Comment by devohp** [comment]
> 
> 
> A workaround for #5 is implemented and everything should work as supposed to work.

It's working! Excellent. Thanks for your weekend time 👍
