### ISSUE TITLE
iOS: New Hash Algorithm in Log Files?

### ISSUE THREAD

**Issue by felixlen** [felixlen/ena_log#5]
With recent iOS update I noticed however, that the algorithm is used by apple to compute the hashes must have changed:
Currently it worked by computing the sha256 hash of the bin file inside the zip archive.

With a recent exposure log from iOS 14.1, I tried to pinpoint two examples (part of log file):
```
"Files" : [
        {
          "Hash" : "D6C9ADEF176488BB7BCFA9F3A01EB5A9F692817441B777A630A1F74131A03CDF",
          "MatchCount" : 0,
          "KeyCount" : 16122,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-23 18:59:04 +0200"
        },
       ...,
        {
          "Hash" : "41444FD9FFAEFDD39A78B11E59DD58EF2146D5F65D39E7607C0E1997712B737F",
          "MatchCount" : 0,
          "KeyCount" : 43934,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-23 18:59:03 +0200"
        }]
```
Looking at the key count:
- first example with 16122 keys most likely refers to `2020-10-22.zip`, where the algorithm sha256 on bin file yields `80f50120713fa19c7ba96639c87ed2dab3f770c4ef8546c4f0ed3804c3c0b834`.
- second example with 43934 keys most likely refers to `2020-10-16.zip`, where the algorithm sha256 on bin file yields `256addf082571d25d9db244b85de520aa8822ad12613dea0433dc7bf736d233f`.

Unfortunately Apple is not very helpful, I did not find explanations beyond [detectExposures](https://developer.apple.com/documentation/exposurenotification/enmanager/3586331-detectexposures) on the log files.

I know that this is completely unrelated to your dashboard, but would very much appreciate if we can find out the hashing algorithm and then update the mapping file / create a new mapping file.

Please feel free to ignore this comment and keep the issue closed if you feel that it is too unrelated to your dashboard.

_Originally posted by @felixlen in https://github.com/janpf/ctt/issues/3#issuecomment-715545706_

**Comment by felixlen** [comment]
Workaround should be good for now until a better understanding is available on how iOS >= 14.1 computes hashes.

**Comment by felixlen** [comment]
The source of this issue is due to changing to country `EUR` instead of country `DE`, see https://github.com/janpf/ctt/issues/8. Once there is a decision on how to proceed, the code here can be adapted accordingly.

**Comment by janpf** [comment]
https://ctt.pfstr.de/json_EUR/filehashes.json ;)

as discussed in janpf/ctt#3 and janpf/ctt#8

**Comment by felixlen** [comment]
@janpf Thanks a lot, much appreciated! Could you kindly allow CORS on that file?

**Comment by janpf** [comment]
> allow CORS on that file

Whoops. Done.

**Comment by felixlen** [comment]
Thanks again, works very well!
