### ISSUE TITLE
iOS: "Invalid DateTime" when uploading with Safari

### ISSUE THREAD

**Issue by devohp** [felixlen/ena_log#6]
Using Safari on iOS uploading the locally exported ExposureChecks file leads to "Schlüsseldatei vom Invalid DateTime mit 16122 Schlüsseln". Same file on Firefox/Windows 10  works as expected ("Schlüsseldatei vom Do., 22. Okt. 2020 mit 16122 Schlüsseln").

**Comment by felixlen** [comment]
Did you try the site before the week-end update with Safari? If yes, I suspect that Safari still has the old version cached. You can check if this is the problem by opening the page in private mode and check if the error disappears.

If it does not disappear, there is indeed a bug.

**Comment by devohp** [comment]
You're right. Sorry!

**Comment by devohp** [comment]
If CWA reports multiple (green?) exposures, the "Invalid DateTime" issue reoccurs: the first exposure works as intended, for the second exposure "Invalid DateTime" is reported (using Safari on iOS and Firefox on Win10)
![screenshot](https://user-images.githubusercontent.com/73386207/97773668-05974500-1b52-11eb-944e-101ac4a12460.png)
.

**Comment by felixlen** [comment]
Thanks for the update. I'm here at a loss, since the semantic of the log file must have been changed, unfortunately it is not documented properly by Apple.

I'm doing the matching based on the hashes and keyCount in the log and use [https://ctt.pfstr.de/json/filehashes.json](https://ctt.pfstr.de/json/filehashes.json) to identify the date. It seems that there is keyfile from the corona warn app server with 26166 keys.

**Comment by felixlen** [comment]
I have implemented a workaround based on the order of the files in the log files. To indicate that the date is guessed, the page displays "wahrscheinlich" before the date.

**Comment by felixlen** [comment]
The source of this problem is identified, see #5. Once #5 is fixed, this should be properly fixed as well, in the meantime, the workaround should do the job.

**Comment by felixlen** [comment]
#5 is fixed and should resolve this issue as well.

**Comment by devohp** [comment]
Works smoothly - thank you!
