### ISSUE TITLE
Tool unusable with CWA 1.9.1 (only iOS)

### ISSUE THREAD

**Issue by Ein-Tim** [felixlen/ena_log#8]
This tool is not usable with iOS devices which run CWA 1.9.1 (v2 of ENF). 
With the change to version 2 of ENF, Apple does not provide any matches in the log (at the moment). 
Please see [this Issue](https://github.com/corona-warn-app/cwa-app-ios/issues/1731) for more information.

**Comment by felixlen** [comment]
Thanks for making me aware of this. As I understand it, there is nothing I can do at the moment?

**Comment by Ein-Tim** [comment]
No, I just wanted to let you know. If you want to, you can merge #9 which creates a new FAQ entry which explains the user why the tool is not working.

**Comment by felixlen** [comment]
Thanks a lot for the FAQ entry, I am very happy to merge it.
